version: '2'

services:
  
  proxy_pool:
    build: .
    container_name: proxy_pool
    ports:
      - "5010:5010"
    links:
      - proxy_redis
    environment:
      DB_CONN: "redis://@proxy_redis:6379/0"
    depends_on:
      - proxy_redis
  
  proxy_redis:
    image: "redis"
    container_name: proxy_redis
  
  scrape:
    build:
        context: ./scrape
        dockerfile: Dockerfile
    volumes:
        - .:/root
    image: scrape
    container_name: scrape
    environment:
      PROXY_POOL: "proxy_pool"  
    depends_on:
      - proxy_pool
      - proxy_redis
